from yacs.config import CfgNode as CN



_C = CN()
_C.MODEL = CN()
_C.MODEL.DEVICE = "cuda"
_C.MODEL.TYPE = ''
_C.MODEL.NAME = ''
_C.MODEL.LAST_LAYER= ''

_C.MODEL.IF_WITH_CENTER = 'no'

_C.MODEL.ID_LOSS_TYPE = 'softmax'
_C.MODEL.ID_LOSS_WEIGHT = 1.0
_C.MODEL.TRIPLET_LOSS_WEIGHT = 1.0

_C.MODEL.LOSS_TYPE = ['ce','triplet']
_C.MODEL.CLIP_LOSS_TYPE = 'constant'
_C.MODEL.DIST_TRAIN = False
_C.MODEL.NO_MARGIN = False
_C.MODEL.IF_LABELSMOOTH = 'on'
_C.MODEL.COS_LAYER = False
_C.MODEL.META_DIMS = []
_C.MODEL.CAMERA_XISHU = 3
_C.MODEL.DEVICE_ID = "0"
_C.MODEL.NONBIO_HEAD=False
_C.MODEL.CLIP_DIM=1024
_C.MODEL.EMBEDDING_DIM=0
_C.MODEL.SUBSPACE_DIM=0
_C.MODEL.BOTTEL_NECK=False
_C.MODEL.NORM_FEAT=False
_C.MODEL.USE_PROJECTION_MLP=True
_C.MODEL.GRL_LOSS_WEIGHT=1.0
_C.MODEL.ORTHO_WEIGHT=0.1

_C.MODEL.PACR_LOSS_WEIGHT = 0.5
_C.MODEL.PACR_MOMENTUM = 0.999
_C.MODEL.PACR_TEMPERATURE = 0.07
_C.MODEL.PACR_HARD_NEGATIVES = 32
_C.MODEL.PACR_WARMUP_EPOCHS = 5
_C.MODEL.CIC_LOSS_WEIGHT = 0.0
_C.MODEL.CIC_TARGET_SIM = 0.85

_C.MODEL.USE_REFINER = False
_C.MODEL.REFINER_HEADS = 8
_C.MODEL.REFINER_DROPOUT = 0.1

_C.MODEL.DISTILL_LOSS_WEIGHT = 1.0
_C.MODEL.TEACHER_FEATURES_PATH = ''

_C.TRAIN = CN()
_C.TRAIN.START_EPOCH = 1



_C.DATA = CN()
_C.DATA.BATCH_SIZE = 8
_C.DATA.DATASET = 'imagenet'
_C.DATA.IMG_HEIGHT = 224
_C.DATA.IMG_WIDTH = 224
_C.DATA.PIN_MEMORY = True
_C.DATA.NUM_WORKERS = 4
_C.DATA.ROOT = ''
_C.DATA.NUM_INSTANCES = 2
_C.DATA.TEST_BATCH = 128
_C.DATA.SAMPLER = 'softmax_triplet'
_C.DATA.AUX_INFO = False

_C.DATA.NOBIO_INDEX=['2']
_C.DATA.BIO_INDEX='0'
_C.DATA.TEXT_MODEL='EVA02-CLIP'
_C.DATA.CAPTION_DIR=''
_C.DATA.TEXT_MODEL_VERSION='EVA02-CLIP-bigE-14'
_C.DATA.SUMMERY_TEXT=True

_C.DATA.PIXEL_MEAN=[0.485, 0.456, 0.406]
_C.DATA.PIXEL_STD=[0.229, 0.224, 0.225]

_C.AUG = CN()

_C.AUG.RC_PROB = 0.5
_C.AUG.RE_PROB = 0.5
_C.AUG.RF_PROB = 0.5


_C.SOLVER = CN()
_C.SOLVER.OPTIMIZER_NAME = "Adam"
_C.SOLVER.MAX_EPOCHS = 100
_C.SOLVER.BASE_LR = 3e-4
_C.SOLVER.WARMUP_LR = 7.8125e-07
_C.SOLVER.LARGE_FC_LR = False
_C.SOLVER.LARGE_FC_FACTOR = 2.0
_C.SOLVER.BIAS_LR_FACTOR = 1
_C.SOLVER.SEED = 1234
_C.SOLVER.MOMENTUM = 0.9
_C.SOLVER.MARGIN = 0.1
_C.SOLVER.CENTER_LR = 0.5
_C.SOLVER.CENTER_LOSS_WEIGHT = 0.0005

_C.SOLVER.WEIGHT_DECAY = 0.0005
_C.SOLVER.WEIGHT_DECAY_BIAS = 0.0005

_C.SOLVER.GAMMA = 0.1
_C.SOLVER.STEPS = (40, 60)
_C.SOLVER.WARMUP_FACTOR = 0.01
_C.SOLVER.WARMUP_EPOCHS = 20
_C.SOLVER.WARMUP_METHOD = "linear"

_C.SOLVER.COSINE_MARGIN = 0.5
_C.SOLVER.COSINE_SCALE = 30

_C.SOLVER.CHECKPOINT_PERIOD = 10
_C.SOLVER.LOG_PERIOD = 100
_C.SOLVER.EVAL_PERIOD = 1
_C.SOLVER.FREEZE_EPOCH=0


_C.TEST = CN()
_C.TEST.WEIGHT = ""
_C.TEST.FEAT_NORM = 'yes'
_C.TEST.TYPE = 'image_only'
_C.TEST.STATUS = False
_C.TEST.NFC_MODE = 'none'
_C.TEST.NFC_K1 = 2
_C.TEST.NFC_K2 = 2
_C.TEST.NFC_ALPHA = 0.7
_C.TEST.NFC_MAX_K = 20
_C.TEST.NFC_APPLY_TO = 'both'

_C.OUTPUT_DIR = ""
_C.OUTPUT_NAME = ""


_C.DATA.SAMPLING_STEP = 64
_C.AUG.SEQ_LEN = 0
_C.AUG.SAMPLING_STRIDE = 4
